chore: add merkle tree util function
gitcoinco/grants-stack pull request #1228
Opened 2023-03-13 22:02 UTC by thelostone-mc

##### Description

##### Refers/Fixes

##### Testing

2023-03-14 05:01 UTC, DanieleSalatti approved these changes
LGTM

2023-03-15 14:27 UTC, nfrgosselin commented
Defer to engineering review

2023-03-16 09:29 UTC, melissa-neira commented
defer to the devs 🫡

2023-03-16 12:05 UTC, bhargavaparoksham requested changes

2023-03-16 12:05 UTC, bhargavaparoksham commented on packages/round-manager/src/context/round/FinalizeRoundContext.tsx
>      );
@thelostone-mc  finalizeRoundToContract function which is called after encoding parameters, calls updateDistribution function via roundImplementation. 
updateDistribution has been removed in roundImp v2.  So this needs to be updated as well for this to work

2023-03-16 17:14 UTC, merged