1259 builder stats 2
gitcoinco/grants-stack pull request #1352
Opened 2023-04-05 01:47 UTC by hmrtn

##### Description

##### Refers/Fixes

##### Testing

2023-04-05 16:06 UTC, boudra approved these changes

2023-04-05 16:39 UTC, melissa-neira requested changes
A few minor changes:
- Add "Gitcoin" text above "Builder" header [Figma](https://www.figma.com/file/78IRtNC6ZRZP8wg6Y2v01U/GPC-x-MMM?node-id=323-4350&t=jncZbJWWhfcqF5Ef-4)
- Margins should be 80px left and right for everything except the image. The image should be aligned to the right (like how it is now). [Figma](https://www.figma.com/file/78IRtNC6ZRZP8wg6Y2v01U/GPC-x-MMM?node-id=272-2404&t=jncZbJWWhfcqF5Ef-4)
- Favicon isn't updated in the preview but it is in prod
<img width="207" alt="Screenshot 2023-04-05 at 18 38 19" src="https://user-images.githubusercontent.com/87520659/230146819-0fbdac98-ce1e-42fd-84d4-5655d6ebe638.png">
The tab preview should also say "Gitcoin | Builder"

2023-04-05 17:40 UTC, hmrtn commented
Fixed the spacing - the favicon should update once it is merged.

2023-04-06 09:11 UTC, melissa-neira commented
@hmrtn can we also add "Gitcoin" above Builder 
<img width="612" alt="Screenshot 2023-04-05 at 19 51 50" src="https://user-images.githubusercontent.com/87520659/230330972-2cc9b076-714e-42ce-93e9-83b5d5d5e978.png">

2023-04-06 16:51 UTC, melissa-neira approved these changes

2023-04-06 17:47 UTC, merged