chore: add warning modal
gitcoinco/grants-stack pull request #1358
Opened 2023-04-05 07:08 UTC by thelostone-mc

##### Description

- add warning modal
- fetch data from subgraph to see if application exists

fixes https://github.com/gitcoinco/grants-stack/issues/1327

2023-04-05 07:56 UTC, thelostone-mc commented on packages/builder/src/actions/projects.ts
>              fetchApplicationStatusesFromContract(
THIS WILL BREAK cause applications are on-chain

2023-04-07 20:31 UTC, hmrtn requested changes
just a couple of small things!

2023-04-07 20:31 UTC, hmrtn commented on packages/builder/src/actions/projects.ts
> +// import RoundImplementationABI from "../contracts/abis/RoundImplementation.json";
same here

2023-04-07 20:31 UTC, hmrtn commented on packages/builder/src/actions/projects.ts
> +          // const roundAddresses = applications.map((app: Application) => app.roundID);
remove deprecated code 🧑‍🚒

2023-04-07 20:31 UTC, hmrtn commented on packages/builder/src/actions/projects.ts
> -            throw response.errors;
there should be some logging if the application fetching fails

2023-04-07 20:31 UTC, hmrtn commented on packages/common/src/index.ts
> +export const convertStatusToText = (applicationStatus: string | number) => {
`convertStatusToText` does not coerce a string into a number for the switch statement. If applicationStatus is a string, the switch statement will not match any cases, and the function will return "PENDING" due to the default case.

Perhaps we should use an enum here for application status. Maybe something like:
```
enum ApplicationStatus {
  PENDING = "0",
  APPROVED = "1",
  REJECTED = "2",
  CANCELLED = "3",
}

export const convertStatusToText = (applicationStatus: string | number): string => {
  // Ensure the applicationStatus is a string
  applicationStatus = applicationStatus.toString();

  switch (applicationStatus) {
    case ApplicationStatus.CANCELLED:
      return "CANCELLED";
    case ApplicationStatus.REJECTED:
      return "REJECTED";
    case ApplicationStatus.APPROVED:
      return "APPROVED";
    case ApplicationStatus.PENDING:
    default:
      return "PENDING";
  }
};
```

2023-04-07 20:31 UTC, hmrtn commented on packages/builder/src/actions/projects.ts
>  // import ProjectRegistryABI from "../contracts/abis/ProjectRegistry.json";
remove this commented import

2023-04-08 05:33 UTC, merged