add: funding settings
gitcoinco/grants-stack pull request #1370
Opened 2023-04-06 02:10 UTC by hmrtn

wip: #1341

- [ ] Pull Settings into a separate form page
- [ ] Update tests
- [ ] Add yup resolver for new fields and updating `Round` type to include new fields

2023-04-07 22:42 UTC, gravityblast commented on packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx
>  });
instead of creating a new file with the same content, can we `git mv ...` so we keep the history of the file?

2023-04-07 23:35 UTC, gravityblast commented on packages/round-manager/src/features/round/__tests__/RoundDetailForm.test.tsx
>  });
oh actually there are other tests in the original file so it makes sense like this, sorry I missed it!

2023-04-10 10:32 UTC, melissa-neira requested changes
Some small changes:
- The gray info bars are missing see [Figma](https://www.figma.com/file/guY5OKIgM18SNa62OysBoe/%5BWIP%5D-Linear-QF-Flow-v2?node-id=21-7339&t=FnTyiKeAJR3A5qAs-4) for reference
- Spacing seems to be off - the support chatbot is under the footer in some white space. This should live in the bottom right corner of the footer.
![screencapture-bafybeigrnn644zsa44rvdvvuxhaeekgooo4r5gkzju3rjlip3cyd44qqmu-on-fleek-co-2023-04-10-12_25_03](https://user-images.githubusercontent.com/87520659/230884826-d55ce2ee-6e7c-4b12-abb1-d2926c51d96c.png)
- I'm getting errors when I'm trying to deploy the round, not sure if relevant
<img width="2093" alt="Screenshot 2023-04-10 at 12 24 00" src="https://user-images.githubusercontent.com/87520659/230884987-bd5a0e55-c5e0-4bc5-a6d4-8c3158a1a123.png">
- as for the hyperlinks, I think @willsputra can help with that 🕺

2023-04-10 11:22 UTC, vacekj commented
@melissa-neira 
- grey info bars only appear when the relevant section is turned on - matching cap etc.
- links added as per will's answers on figma
- intercom spacing - please share your intercom app id with me in DMs
- round creation issue - noted and investigating

2023-04-10 12:17 UTC, vacekj commented
@melissa-neira I can't repro your round creation issue. Could you please verify that your application start time has not already passed? this was my error at first.

2023-04-10 12:23 UTC, melissa-neira commented
@vacekj I went back to check and now the program I created before doesn't appear nor can I create a new program 😖 happy to pair with you to figure it out
<img width="2053" alt="Screenshot 2023-04-10 at 14 20 29" src="https://user-images.githubusercontent.com/87520659/230900684-a2979fbe-b2ce-4523-ae12-3a00916b13c0.png">

2023-04-10 13:41 UTC, vacekj commented
two problems:

- [ ] old rounds and programs are not appearing and not fetching even if you visit directly
- [ ] round name is not displayed in both round detail apage and program detail page.

2023-04-10 17:45 UTC, nfrgosselin commented
@hmrtn @vacekj I'm getting an error when I try to deploy the round contract. The payout and voting contracts go through without error though: 
![image](https://user-images.githubusercontent.com/15041635/230960082-14b6e89e-622f-4de5-900f-4ced37280c4e.png)

2023-04-10 17:53 UTC, vacekj commented
@nfrgosselin acked and investigating, we have an idea where this might be coming from.

2023-04-10 18:32 UTC, vacekj commented
@nfrgosselin works for dai on goerli now, please verify on your end too after the build passes.

2023-04-10 18:48 UTC, nfrgosselin approved these changes

2023-04-10 18:51 UTC, merged