Rework and extend Round Results Page
gitcoinco/grants-stack pull request #1552
Opened 2023-04-21 16:02 UTC by vacekj

2023-04-24 10:30 UTC, boudra commented
I noticed you're installing `papaparse`. We already have CSV libraries installed, check the `package.json`.

2023-04-24 17:45 UTC, vacekj commented
> I noticed you're installing `papaparse`. We already have CSV libraries installed, check the `package.json`. Also I don't think we need to parse CSV in the front end to implement this feature but maybe I am missing context.

Removed papaparse in favour of csv-parse which we already had installed (can be switched back to papaparse, but only one should be used at a time). 

CSV Parsing isn't necessary for the ACs in #1455, @hmrtn was your intention to bundle all the stories for this page into this PR? I would advise against this, for reasons previously discussed, and instead keep the 1:1:1 Ticket - Branch - PR rule. I see that some of the ACs from the other tickets are already ticked off in this PR, so please update the tickets to mention the ACs were moved here.

2023-04-24 23:18 UTC, hmrtn commented
In order to proceed with download and tables we need the matching calculation handlers in the allo indexer client.

2023-04-25 21:30 UTC, hmrtn commented
NOTE: This hardcodes `isBeforeRoundEndTime = false`. To resolve this, changes are required in the indexer. Namely the client `Round type` does not implement the `roundStart/Endtime`.
This is necessary to merge as the tests will fail otherwise.

2023-04-25 21:31 UTC, hmrtn commented
Also see the TODO's. More tickets will be needed to close these out - related to uploading, finalizing, etc //

2023-04-25 21:51 UTC, boudra requested changes

2023-04-25 21:51 UTC, boudra commented on packages/round-manager/.run/RM All Tests.run.xml
what is this file? is it an IDE file?

2023-04-25 21:51 UTC, boudra commented on packages/round-manager/src/features/round/ViewRoundResults_old.tsx
we shouldn't have these _old files

2023-04-25 21:53 UTC, gravityblast commented on packages/round-manager/.run/RM All Tests.run.xml
>      <scope-kind value="ALL" />
we need to remove this JetBrain file

2023-04-25 21:54 UTC, gravityblast commented on packages/round-manager/package.json
> +    "allo-indexer-client": "github:gitcoinco/allo-indexer-client#61d050e82e58cc8e55f79faf8fbb3d0236d8ff50",
let's create a PR on that repo as well

2023-04-25 21:55 UTC, boudra commented
before we merge let's make sure the round stats work using some of the current mainnet rounds

2023-04-25 21:56 UTC, gravityblast commented on packages/round-manager/package.json
> +    "allo-indexer-client": "github:gitcoinco/allo-indexer-client#61d050e82e58cc8e55f79faf8fbb3d0236d8ff50",
ah I see this is already in main, let's create a new PR if we need more changes

2023-04-25 22:05 UTC, boudra commented
> NOTE: This hardcodes `isBeforeRoundEndTime = false`. To resolve this, changes are required in the indexer. Namely the client `Round type` does not implement the `roundStart/Endtime`.
> This is necessary to merge as the tests will fail otherwise. 

is something blocking you from doing this straight away? the allo indexer client can be updated and pushed in a branch, then we update the commit hash here

2023-04-25 23:44 UTC, hmrtn commented
here is the allo indexer commit in the latest changes: https://github.com/gitcoinco/allo-indexer-client/commit/52be896010b22083390ca3ec6e05da9f97a4dd19

2023-04-25 23:45 UTC, hmrtn commented on packages/round-manager/.run/RM All Tests.run.xml
yes - jetbrains things

2023-04-26 09:12 UTC, boudra commented on packages/round-manager/.run/RM All Tests.run.xml
removed

2023-04-26 09:12 UTC, boudra commented on packages/round-manager/src/features/round/ViewRoundResults_old.tsx
removed

2023-04-26 09:12 UTC, boudra commented on packages/round-manager/.run/RM All Tests.run.xml
>      <scope-kind value="ALL" />
removed

2023-04-26 09:21 UTC, boudra approved these changes

2023-04-26 09:43 UTC, vacekj commented
<img width="196" alt="image" src="https://user-images.githubusercontent.com/10381200/234537135-bbe513b2-cd71-4ab8-9302-087fc68b2589.png">
you love to see it 🔥

2023-04-26 10:04 UTC, merged