[WIP] 1587 - Explorer mobile view
gitcoinco/grants-stack pull request #1670
Opened 2023-05-01 18:28 UTC by codenamejason

2023-05-02 19:21 UTC, thelostone-mc approved these changes

2023-05-02 23:06 UTC, hmrtn requested changes
A number of tests fail. Namely, the add/remove from cart test id's are missing on the test render. Resolve for approval :)

See https://github.com/gitcoinco/grants-stack/blob/dfee6f3cee6b74109dcf83d07a95106de92954fc/packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx#L308 and all other mentions of `add-to-cart` and `remove-from-cart`

2023-05-03 11:58 UTC, melissa-neira approved these changes

2023-05-03 15:53 UTC, michellema1208 reviewed
hey @codenamejason - I did a quick pass on this PR just now and noticed that the copy on the Passport banner is outdated. It should be consistent with the copy that was included in this PR: https://github.com/gitcoinco/grants-stack/issues/1516 

Can we make sure it's consistent? Want to make sure we don't override copy updates. Thank you Jason!

2023-05-03 16:32 UTC, codenamejason commented
@michellema1208 this is the copy I put:

<img width="582" alt="Screenshot 2023-05-03 at 12 31 49 PM" src="https://user-images.githubusercontent.com/9419140/235980804-257321b6-4e19-4272-a4a8-783ff927aa0b.png">

Using this [Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?type=design&node-id=526%3A14125&t=zrj3wxvYigQd5EmA-1)

2023-05-03 16:43 UTC, hmrtn approved these changes

2023-05-03 18:02 UTC, michellema1208 approved these changes

2023-05-03 18:18 UTC, merged