feat: upload csv overrides
gitcoinco/grants-stack pull request #1687
Opened 2023-05-03 13:24 UTC by boudra

##### Description

resolves [#1474](https://github.com/gitcoinco/grants-stack/issues/1474)

##### Refers/Fixes

##### Testing

2023-05-04 18:55 UTC, hmrtn approved these changes
lgtm

2023-05-04 19:30 UTC, nfrgosselin requested changes
I found two issues further explained in this [Loom](https://www.loom.com/share/257f1aa16d534e21be059016d8e275be)

1) The matching coefficients don't seem to be taking into account the round's Passport settings
2) The upload function seems to be looking for the wrong column name

2023-05-08 10:11 UTC, vacekj commented on packages/round-manager/tailwind.config.js
> +  content: ["./src/**/*.{js,jsx,ts,tsx}", "../common/src/**/*.{js,jsx,ts,tsx}"],
not sure if this is the right way to do it but it isn't terrible and it's clear what it's doing. fine by me

2023-05-08 10:23 UTC, vacekj approved these changes

2023-05-08 17:37 UTC, nfrgosselin approved these changes

2023-05-08 17:51 UTC, melissa-neira approved these changes

2023-05-08 17:51 UTC, merged