remove husky and lint staged, disable git hooks
gitcoinco/grants-stack pull request #1883
Opened 2023-05-26 16:52 UTC by vacekj

fixes #1814 

left in a lefthook to trigger prettier for those who want

2023-05-30 15:15 UTC, boudra requested changes
Since hooks are not installed automatically now, we should add information of how to use lefthook in the README and once we merge we can share the link to the team so they know how to enable it if they want to.

2023-05-31 12:26 UTC, melissa-neira commented
defer to eng review 🕺

2023-05-31 22:00 UTC, gravityblast submitted a review, later dismissed

2023-05-31 22:02 UTC, gravityblast commented
I think we should put the prettier check in CI but it's longer, let start with what @boudra said

2023-06-05 17:09 UTC, DanieleSalatti approved these changes

2023-06-05 18:13 UTC, merged