Explorer: automatically update cart across all tabs if a project is added/removed to cart
gitcoinco/grants-stack pull request #1886
Opened 2023-05-29 14:39 UTC by bhargavaparoksham

##### Description

Automatically update cart across all tabs if a project is added/removed to cart]

##### Refers/Fixes

fixes #1689

##### Testing

2023-05-30 20:18 UTC, michellema1208 approved these changes
@bhargavaparoksham LGTM! Great work here [🔥](https://emojipedia.org/fire/)

2023-05-31 09:11 UTC, boudra requested changes

2023-05-31 09:11 UTC, boudra commented on packages/grant-explorer/src/features/common/Navbar.tsx
> +      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
you can surround the body of this function with an `if(roundId) { }` instead of doing a null assertion

2023-05-31 09:59 UTC, boudra approved these changes

2023-05-31 10:07 UTC, merged