fix: builder project preview
gitcoinco/grants-stack pull request #1916
Opened 2023-06-02 15:45 UTC by hmrtn

fixes #1891 By restructuring the `showTabs` boolean logic. If true, the about section will be shown inside of the navigable tab panel, otherwise just show the about section (e.g. when previewing).

2023-06-02 18:48 UTC, michellema1208 commented
@hmrtn Can you point me to the preview link for Builder that I can use to test? I culled the build details page (https://github.com/gitcoinco/grants-stack/pull/1916/checks?check_run_id=13962072658) but couldn't find it

2023-06-05 13:40 UTC, michellema1208 requested changes
@hmrtn - this is overall looking good! One minor piece of UX feedback: it looks like the padding + margin between the "Description" label and the actual test of description does not match what we have in the Figma. 

**Figma: padding is 8px with no top margin** 
<img width="1196" alt="Screen Shot 2023-06-05 at 9 30 33 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/945fe444-e695-4f0c-aee3-1fe4981ee6b9">


**In Development: it looks like padding is 24px and there is a top margin (it looks like what we need is to remove the top-margin in the .prose class -> see second screenshot)** 

<img width="1432" alt="Screen Shot 2023-06-05 at 9 34 29 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/5d963d37-63c8-42b6-8516-75c9ce39bee0">

<img width="1439" alt="Screen Shot 2023-06-05 at 9 33 14 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/8163e778-1090-499b-9a7d-84923f62ae1b">

2023-06-06 11:14 UTC, bhargavaparoksham approved these changes

2023-06-06 19:49 UTC, michellema1208 submitted a review, later dismissed

2023-06-07 09:28 UTC, gravityblast requested changes

2023-06-07 09:28 UTC, gravityblast commented on packages/builder/tailwind.config.js
> +            paddingTop: '8px',
I would avoid having a global padding top for all the `p` tags, lets add it specifically where we need it. 
And in general, do we really need a padding top here, or better having a padding top for the container and maring bottom for each paragraph?

2023-06-07 09:28 UTC, gravityblast requested changes
I left a comment on the css part

2023-06-07 11:13 UTC, melissa-neira submitted a review, later dismissed
lgtm!

2023-06-13 12:40 UTC, melissa-neira approved these changes

2023-06-13 12:55 UTC, vacekj approved these changes

2023-06-15 15:19 UTC, vacekj approved these changes

2023-06-15 15:20 UTC, vacekj commented
@gravityblast I'm going to go ahead and merge this as your comment was addressed in the last commit, and we have approvals from the rest of the team.

2023-06-19 09:47 UTC, gravityblast approved these changes

2023-06-19 09:59 UTC, merged