[1583] feat: hide past rounds from builder project page
gitcoinco/grants-stack pull request #1935
Opened 2023-06-09 23:18 UTC by DanieleSalatti

##### Description

What it says on the tin.

##### Refers/Fixes

Closes #1583 

##### Testing

Tested locally

2023-06-13 12:32 UTC, gravityblast commented on packages/builder/src/components/grants/About.tsx
> +          return <ApplicationCard applicationData={cardData} />;
@DanieleSalatti don't we still need a key here?

2023-06-13 12:36 UTC, gravityblast requested changes
with this implementation we are adding a hidden class name directly in the card component, which means we can never use the Card component with past applications, even in other possible pages. 

Instead of rendering all the applications and hiding them, I would suggest to move the logic in the `map` loop and skipping the Card component for past rounds

2023-06-14 11:33 UTC, melissa-neira requested changes
While testing, I noticed that each project that I had rendered the application column differently. 
This project rendered correctly (although it took a few extra seconds to load):
![screencapture-bafybeiatebykyd3tudj75zfy2owwytuo5r4zihgnavkdsvs5janlp2xzau-on-fleek-co-2023-06-14-13_29_53](https://github.com/gitcoinco/grants-stack/assets/87520659/9e49aa07-5218-4a9f-aeb0-5c663c0c0d2d)
This project's application column was empty:
![screencapture-bafybeiatebykyd3tudj75zfy2owwytuo5r4zihgnavkdsvs5janlp2xzau-on-fleek-co-2023-06-14-13_29_00](https://github.com/gitcoinco/grants-stack/assets/87520659/06c43afd-81ab-464d-aa89-eda93404c2c3)
This project didn't even have a "my applications" column.
![screencapture-bafybeiatebykyd3tudj75zfy2owwytuo5r4zihgnavkdsvs5janlp2xzau-on-fleek-co-2023-06-14-13_29_18](https://github.com/gitcoinco/grants-stack/assets/87520659/20d8531a-9fee-4c0f-890b-1aa97e596885)

Anyone else experiencing this?

2023-06-15 14:18 UTC, DanieleSalatti commented
I see what the problem is, that needs to be fixed.

Two questions:
* Would it be better to rename "My Applications" with current applications? So it's more obvious why applications disappear.
* When no applications are displayed, should we hide the column or should we leave the header? Since it takes some time to load the applications (even when there is only one), I think we should show the header with a spinner when loading, and then a message of some sort if there are no active rounds.

Thinking about it, maybe we leave "My Applications" at the top, never hide the column, and add "This grant has not applied to active rounds yet" as a message then the column is empty?

@melissa-neira

2023-06-15 15:14 UTC, vacekj commented
@melissa-neira @DanieleSalatti it would be great if we could start using loading skeletons instead of spinners. https://www.npmjs.com/package/react-loading-skeleton. It looks much better than a generic spinner.

2023-06-15 22:53 UTC, willsputra commented
> Thinking about it, maybe we leave "My Applications" at the top, never hide the column, and add "This grant has not applied to active rounds yet" as a message then the column is empty?

@DanieleSalatti I like the idea! created the updated Figma screen here: https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Builder-S17?type=design&node-id=5183-45653&t=x3oIeUUcFuwdjU3g-4

@melissa-neira @michellema1208 would love your eyes especially on the copy! feel free to edit :)

2023-06-16 12:53 UTC, melissa-neira commented
@willsputra looks good to me!

2023-06-19 10:03 UTC, gravityblast commented on packages/builder/src/actions/rounds.ts
> +      console.log("DASA loading round", address, chainId);
@DanieleSalatti we have to remove this log

2023-06-19 17:06 UTC, boudra commented on packages/builder/src/components/grants/About.tsx
> +  useEffect(() => {
we could do `const appsToShow = useMemo(..)` here instead of `useEffect + useState`

2023-06-19 22:44 UTC, DanieleSalatti commented
> > Thinking about it, maybe we leave "My Applications" at the top, never hide the column, and add "This grant has not applied to active rounds yet" as a message then the column is empty?
> 
> @DanieleSalatti I like the idea! created the updated Figma screen here: https://www.figma.com/file/obBzCCL8KwoTlVBb5g3ccN/Builder-S17?type=design&node-id=5183-45653&t=x3oIeUUcFuwdjU3g-4
> 
> @melissa-neira @michellema1208 would love your eyes especially on the copy! feel free to edit :)

Looks good, on it.

2023-06-21 22:44 UTC, DanieleSalatti commented
Tests failing now that I'm using the chakra skeleton.
Relevant: https://github.com/chakra-ui/chakra-ui/issues/6036

2023-06-23 06:03 UTC, bhargavaparoksham approved these changes
LGTM.

2023-06-26 22:39 UTC, DanieleSalatti commented
> @DanieleSalatti loading time is really long, over 2 minutes on my end. Project application status appears like this: 
[...]
 It still hasn't loaded yet 😅

I'll take a look to see if we are doing any unnecessary operation. We fetch that data from IPFS, which can be slow, but 2 minutes is a really long time.

2023-08-30 10:09 UTC, vacekj commented
@meglister @michellema1208 same request - can you please confirm that the issue this PR was trying to solve in the first place is still present in our latest deployment? If so, then I can drive this PR over the line.

2024-02-22 11:57 UTC, thelostone-mc commented
Closing this out as the PR has gone stale. Will revisit when if and when it gets added to the backlog

2024-02-22 11:57 UTC, closed without merging