Explorer: Add transaction information per donation on Donation History page
gitcoinco/grants-stack pull request #1966
Opened 2023-06-20 13:56 UTC by bhargavaparoksham

##### Description

As a DONOR
I want to see the transaction information for my donation
So that I can check the transaction on-chain

##### Refers/Fixes

fixes #1899 

##### Testing

2023-06-22 08:43 UTC, melissa-neira requested changes
Functionally, this looks good to me. However the spacing in the UI doesn't match the designs in figma. 
This how the page looks on my screen:
<img width="1836" alt="Screenshot 2023-06-22 at 10 39 43" src="https://github.com/gitcoinco/grants-stack/assets/87520659/b09bb30a-6361-4fec-9025-267011b3386f">
There's a lot of white space to the right, making this page look a bit wonky.

In Figma, the columns and rows span the width of the page. Also, the spacing between the Donation Impact and Donation History sections is quite tight. Can you please update it so it looks like this? Thank you
![No matching](https://github.com/gitcoinco/grants-stack/assets/87520659/bc89437a-e5e5-401c-a0ff-a068ff3c20dc)

2023-06-23 20:38 UTC, michellema1208 approved these changes

2023-06-26 10:17 UTC, melissa-neira commented
@bhargavaparoksham can you please add more space between the page's content and the footer? It would look better if the footer had more breathing room. See [Figma](https://www.figma.com/file/cgsZMTG71f2Hf89J38simK/Explorer-S17?type=design&node-id=3022-64341&mode=design&t=CSjDoYVXm2ttJXkq-4) for reference

2023-06-26 11:28 UTC, bhargavaparoksham commented
@melissa-neira added the space b/w content & footer as requested. Can you review it now.

2023-06-26 11:50 UTC, melissa-neira approved these changes

2023-06-26 13:29 UTC, vacekj approved these changes

2023-06-26 13:48 UTC, merged