feat: start adding arbitrum chain to apps
gitcoinco/grants-stack pull request #2266
Opened 2023-08-25 22:01 UTC by vacekj

##### Description

##### Refers/Fixes

##### Testing

2023-08-30 14:52 UTC, bard approved these changes

2023-08-31 10:10 UTC, bard requested changes
Tests are currently failing.

2023-09-01 18:12 UTC, bard approved these changes

2023-09-01 18:13 UTC, michellema1208 approved these changes

2023-09-01 19:04 UTC, merged