chore: add polygon & mumbai support
gitcoinco/grants-stack pull request #2363
Opened 2023-09-20 09:58 UTC by vacekj

fixes #2130

2023-09-20 14:08 UTC, bhargavaparoksham submitted a review, later dismissed

2023-09-20 17:45 UTC, michellema1208 commented
hey @vacekj ! ty for also getting Polygon work started! Sharing results from QA testing: 

### Builder 
- [ ] Successfully created a round but round is not indexed on Builder (I don't see my Polygon project on My Projects) 

Transaction: https://polygonscan.com/tx/0x5de57774241aa90abd7082681117f5b1fde386ca20169603a54325d84b962e7e 

### Manager 
- [ ] Not seeing Polygon as a supported network when I load: https://manager-git-2130-polygon-add-to-gs-grants-stack.vercel.app/ 
<img width="1440" alt="Screen Shot 2023-09-20 at 1 23 27 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/26fdd663-1278-4e8b-8bb7-0f101e2f43e2">

Blocked on testing Explorer for now as well - let me know if I can help debug!

2023-09-21 09:09 UTC, gravityblast requested changes

2023-09-21 10:34 UTC, vacekj commented
@gravityblast fixed the addresses, thank you
@michellema1208 you may now retest, thanks for your patience

2023-09-21 10:46 UTC, gravityblast approved these changes

2023-09-21 13:27 UTC, michellema1208 commented
@vacekj thank you so much! Confirming that I'm now able to create a project + see it after it's created on Builder. 

On Manager, I'm seeing Polygon as a supported network now, but not seeing options to create a Program/round -- wondering if this might be missing env vars as well? 

<img width="1438" alt="Screen Shot 2023-09-21 at 9 25 59 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/d8b50c5a-3f17-4a0a-bd59-feb0fde517cc">

2023-09-21 15:58 UTC, michellema1208 submitted a review, later dismissed

2023-09-21 16:58 UTC, michellema1208 approved these changes

2023-09-21 18:03 UTC, gravityblast approved these changes

2023-09-21 18:05 UTC, merged