chore: simplify payout tokens handling
gitcoinco/grants-stack pull request #2665
Opened 2023-11-22 09:27 UTC by vacekj

## PR checklist

For every PR, make sure that these statements are true:
  - [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
  - [x] Doesn't contain type casts and non-null assertions.
  - [x] Doesn't add `@ts-ignore`.
  - [x] Doesn't disable lints.
  - [x] Doesn't use `useState` just for computation - use plain variables instead.
  - [x] Splits components into pure components that don't depend on external state or hooks.
  - [x] Avoid embedding components within other components
  - [x] Doesn't propagate optional values without good reason, doesn't mark property values as optional if that doesn't represent reality.
  - [x] Doesn't duplicate existing code.
  - [x] Parses out-of-domain data - this includes user input, API respones, on-chain data etc.
  - [x] Doesn't contain commented out code.
  - [x] Doesn't contain skipped or empty tests.
  - [x] If this PR adds/updates any feature, it adds/updates its test script

Subjective - at the discretion of the reviewers
- Does things as simply as possible, but not simpler.
- Doesn't reinvent the wheel or create premature abstractions.

##### Description

##### Refers/Fixes

fixes #2271

2023-11-22 11:07 UTC, melissa-neira approved these changes
I defer to the eng team 🤝

2023-11-22 11:21 UTC, bhargavaparoksham requested changes

2023-11-22 11:21 UTC, bhargavaparoksham commented on packages/round-manager/src/features/api/payoutTokens.ts
@vacekj can we move this to common instead of in manager?

2023-11-24 08:41 UTC, carlbarrdahl approved these changes
looks good!

2023-12-19 10:41 UTC, merged