Add support for scroll testnet
gitcoinco/grants-stack pull request #2797
Opened 2024-01-09 13:55 UTC by bhargavaparoksham

Fixes: #2777 

## Description

Add support for scroll testnet

## Checklist

This PR:

- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-01-10 14:50 UTC, vacekj commented on packages/common/src/chains.ts
> +export const scrollTestnet: Chain = {
scroll sepolia should be available as a chain from viem/chains here.

2024-01-10 14:51 UTC, vacekj commented on packages/grant-explorer/src/features/api/utils.ts
> +    logo: TokenNamesAndLogos["DAI"],
if we have a test logo let's use that instead of DAI to not mislead the user

2024-01-10 14:51 UTC, michellema1208 commented
hey @bhargavaparoksham - running into a few issues:

- [ ] I'm not able to apply to a round on Scroll, and it looks like it's due to a LIT error: 

<img width="1432" alt="Screen Shot 2024-01-10 at 9 44 17 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/62a87bce-e2da-47e6-b6cb-eaaa6dac8578">

- [ ] The Builder "My Projects" page generally takes a really long time to load, and also seems to be missing Scroll Sepolia projects  

<img width="1437" alt="Screen Shot 2024-01-10 at 9 45 55 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/2c7c354d-a8d6-42df-9fd3-7a2097f62d06">

2024-01-10 14:51 UTC, vacekj requested changes
scrollTestnet is ambiguous as a chain name, since there was previously a scroll alpha testnet, and there will be new testnets in the future. let's call it `scrollSepolia` to disambiguate.

2024-02-23 11:08 UTC, gravityblast commented
closing for now since LIT doesn't support scroll testnet

2024-02-23 11:08 UTC, closed without merging