fetch Allo V2 programs from the indexer
gitcoinco/grants-stack pull request #2871
Opened 2024-02-02 13:52 UTC by bhargavaparoksham

Fixes: #2816 

## Description

fetch Allo V2 programs from the indexer

## Checklist

This PR:

- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-02-02 18:22 UTC, codenamejason commented on packages/data-layer/src/queries.ts
> +export const getProfilesByUser = gql`
We have one for projects below called getProjectsByAddress that is very similar - I think our naming is starting to bleed about.

2024-02-07 15:27 UTC, vacekj approved these changes

2024-02-12 16:01 UTC, michellema1208 reviewed
hey @bhargavaparoksham - I'm able to see the profile I created on Builder on Manager, but not able to open the profile on Manager. Is that expected / out of scope for this PR? Otherwise, I would expect to be able to open the profile and be able to create rounds under it (once the "create round on v2" PR is ready). 

<img width="1435" alt="Screen Shot 2024-02-12 at 10 59 00 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/0547a6d6-44bd-4801-924f-c01dcb26fa7e">

<img width="1439" alt="Screen Shot 2024-02-12 at 10 58 48 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/72c9ef0f-13d4-4128-bc99-f61ab62385e0">

Manager link: https://manager-staging-git-manager-2816-grants-stack.vercel.app/#/program/0x16aaa61bcdf4445bad79cc671fa513c357b218b13720d6e2adb70af404d2007b

2024-02-13 11:52 UTC, boudra requested changes
not sure i understand why both queries that are exactly the same, have different types and if statements, where one is being mapped to the exact same type, it feels like there's a lot of repetition that could cause human error if someone would forget to update a type or a query

would something like this work?

```typescript
const getProgramsByUserAndTag = gql`
  query ($address: String!, $chainId: Int!, $filterByTag: String ) {
    projects(
      filter: {
        tags: { contains: $filterByTag }
        roles: { some: { address: { equalTo: $address } } }
        chainId: { equalTo: $chainId }
      }
    ) {
      id
      chainId
      metadata
      metadataCid
      tags
      roles {
        address
        role
        createdAtBlock
      }
    }
  }
`;

let response: { projects: Program[] } = { projects: [] };

response = await request(
  this.gsIndexerEndpoint,
  getProgramsByUserAndTag,
  { ...requestVariables, filterByTag: alloVersion === "allo-v2" ? "allo-v2" : "program" },
);

return response.projects;
```

2024-02-13 11:52 UTC, boudra commented on packages/data-layer/src/queries.ts
> +export const getV1ProjectsByUser = gql`
these two separate queries are exactly the same you could have a single query here that receives a tag to filter by, the caller can use program for v1 or allo-v2 for v2

2024-02-15 11:02 UTC, boudra approved these changes

2024-02-15 11:02 UTC, merged