Canonical Projects
gitcoinco/grants-stack pull request #2962
Opened 2024-02-19 12:58 UTC by 0xKurt

### Description 

This PR speed up the builder project and reduces graph calls by 3x.
It is meant to allow you to create a linked project behind the scenes when you apply to a round on a different chain.
This PR should be tested only for QF 

#### Allo V1

- [x] Create Project
- [x] Apply To Round (same chain)
- [x] Apply To Round (different chain)
- [x] View Application
- [x] Vew Project / Stats / Rounds
- [x] Edit a Project

####  Allo V2

- [x] Create Project
- [x] Apply To Round (same chain)
- [x] Apply To Round (different chain)
- [x] Apply To Round (canonical project in diff chain but linked project exists)
- [x] View Application 
- [x] Vew Project / Stats / Rounds
- [x] Edit a Project

#### Open rounds to apply:
[v1 round](https://builder-staging-git-canonical-projects-grants-stack.vercel.app/#/chains/11155111/rounds/0x0a651f9aba8be2280557013d0bcdfeeb44294b19) (staging link)
[v2 round](https://builder-staging-git-canonical-projects-grants-stack.vercel.app/#/chains/11155111/rounds/20) (staging link)

Fixes: https://github.com/gitcoinco/grants-stack/issues/2857
Fixes: https://github.com/gitcoinco/grants-stack/issues/2928
Fixes https://github.com/gitcoinco/grants-stack/issues/2911

Video part 1: https://drive.google.com/file/d/1CC-6xqcAQXH6Gv4yQLAnex2wZSEGwWPr/view?usp=drive_link
Video part 2: https://drive.google.com/file/d/1lb6515qdGdlNlrhrRoFHbrb4VHmdSIa_/view?usp=drive_link

2024-02-21 01:06 UTC, codenamejason commented on packages/data-layer/src/data-layer.test.ts
> +    // if (data?.projects) expect(data.projects.length).toBeGreaterThan(0);
todo

2024-02-22 10:55 UTC, boudra requested changes
i see some console logs and todos, please do self review first and let me know

2024-02-22 15:38 UTC, codenamejason commented on packages/builder/src/reducers/roundApplication.ts
> +  RoundApplicationActions,
This naming seems odd here 🤔

2024-02-22 15:41 UTC, codenamejason approved these changes
Nice work everyone 🌱

2024-02-22 18:02 UTC, michellema1208 approved these changes
@0xKurt / @codenamejason / @thelostone-mc -- TY so much for adding the v1 and v2 staging links! I used both of those and was able to successfully apply cross-chain. 

v1: used a PGN testnet project to apply to Sepolia round. Successful tx: https://sepolia.etherscan.io/tx/0x22d5bad744dd1e6af59acda82405036e0bb31580aad0a06f140e30541cde1d77

v2: used Polygon Mumbai project to apply to Sepolia round. Successful tx: https://sepolia.etherscan.io/tx/0x7590f7d88136a0247071a9d97e671ccc15c11201b4795a5d2d9684a5ec069d2a

2024-02-22 18:16 UTC, merged

2024-02-23 11:05 UTC, boudra commented on packages/data-layer/src/data-layer.ts
> +    roundId: Lowercase<Address>;
round ID is not always and address, string would be more appropriate here

2024-02-23 11:05 UTC, boudra commented on packages/data-layer/src/data-layer.ts
> +  }): Promise<ProjectApplication[] | undefined> {
this function never returns undefined

2024-02-23 11:05 UTC, boudra commented on packages/data-layer/src/data-layer.ts
> +    const response: { applications: any } = await request(
any are not allowed

2024-02-23 11:07 UTC, boudra commented on packages/data-layer/src/data-layer.ts
> +  async getApplicationStatusByRoundIdAndCID({
this function doesn't seem to be used

2024-02-23 11:08 UTC, boudra commented on packages/data-layer/src/data.types.ts
> +  project?: {
this should be it's own type like ProjectApplicationWithProject

2024-02-23 11:08 UTC, boudra commented on packages/builder/src/components/rounds/ViewApplication.tsx
> +      // applicationError,
commented out code shouldn't be in production