chore: move mrc voting to allo sdk
gitcoinco/grants-stack pull request #2987
Opened 2024-02-21 21:52 UTC by vacekj

Fixes: #2817 

## Description

moves the donation part and related types of voting using MRC on Allo v1 to the allo sdk.

## Checklist

This PR:

- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't disable eslint rules.
- [x] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [x] Doesn't contain commented out code.
- [x] If adding/updating a feature, it adds/updates its test script on Notion.

2024-02-22 15:28 UTC, gravityblast commented
I tried the checkout with one project in the cart from this test round and it fails:

<img width="1101" alt="Screenshot 2024-02-22 at 16 26 49" src="https://github.com/gitcoinco/grants-stack/assets/1059/ccd07215-a7b9-43fb-8d45-190cfb4478ed">

2024-02-22 15:29 UTC, gravityblast requested changes
added a comment above with an error

2024-02-22 15:38 UTC, gravityblast commented on packages/common/src/allo/addresses/mrc.ts
> +    "0x0x62a850d7805f3Ae382C6eEf7eEB89A31f68Ce2d5",
there's a double `0x` prefix

2024-02-22 16:00 UTC, vacekj commented on packages/common/src/allo/addresses/mrc.ts
> +    "0x0x62a850d7805f3Ae382C6eEf7eEB89A31f68Ce2d5",
good catch, thanks!

2024-02-22 16:44 UTC, gravityblast commented
it's still failing to send the tx at checkout

2024-02-22 17:14 UTC, gravityblast commented
the current step is no longer animated (the blue one)
![Uploading Screenshot 2024-02-22 at 18.10.52.png…]()

2024-02-22 23:21 UTC, gravityblast commented
I still have the same issue following the steps above

2024-02-22 23:55 UTC, gravityblast commented on packages/grant-explorer/src/features/round/ViewCartPage/MRCProgressModalBody.tsx
> +                      className="relative z-10 w-6 h-6 flex items-center justify-center bg-teal-500 rounded-full "
there's a space added here

2024-02-23 21:41 UTC, michellema1208 requested changes
@vacekj - I tested just now and can confirm that donations on Sepolia are working (following @gravityblast's instructions above) and I also additionally tested MRC with a Sepolia + Optimism project in cart - also worked.

However, noted one UX quirk that seems to be introduced by this PR as its not happening in prod -- when you donate to two or more rounds, in the horizontal progress bar in the checkout modal, when the first step is completed, the check continues to flash and appears to enlarge. Whereas in prod, the check remains constant. 

This PR: 
<img width="1436" alt="Screen Shot 2024-02-23 at 4 33 34 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/3894ef83-d175-44a2-a136-eefa83de7fab">

Sepolia round: https://explorer-staging-git-2817-explorer-move-v1-d7e21b-grants-stack.vercel.app/#/round/11155111/0x0a651f9aba8be2280557013d0bcdfeeb44294b19 
Optimism round: https://explorer-staging-git-2817-explorer-move-v1-d7e21b-grants-stack.vercel.app/#/round/10/0xd52b1ecf94dcc8036180ca2e6b63e05d78bc4cde 

Prod: 
<img width="1434" alt="Screen Shot 2024-02-23 at 4 35 43 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/a4c07277-0908-4373-94d5-31f6c88c31e3">

Prod Optimism round: https://explorer.gitcoin.co/#/round/10/0xd52b1ecf94dcc8036180ca2e6b63e05d78bc4cde
Prod Base round: https://explorer.gitcoin.co/#/round/8453/0xb84909f60b31db387baea1ea8c6dfe1b16100eee

I know it's super small, but want to callout even subtle UX regressions early so we don't create more debt for ourselves in the future. Feel free to test yourself with the links provided above!

+@melissa-neira to test as well to help callout any other UX/design notes!

2024-02-27 16:15 UTC, michellema1208 commented
@vacekj just to ask explicitly: is seeing the donations on the Donation History page in scope for this PR?

2024-02-27 21:03 UTC, vacekj commented
@michellema1208 donation history page shouldn't be affected by this PR at all - that's an indexer-populated page.

2024-02-28 13:01 UTC, boudra requested changes

2024-02-28 16:41 UTC, michellema1208 commented
> @michellema1208 donation history page shouldn't be affected by this PR at all - that's an indexer-populated page.

@vacekj cool, thank you! Does that mean that donations made within this PR would show up on the Donation History page? Or is additional Indexer work needed in order to support that? +@boudra

2024-02-29 19:19 UTC, boudra commented
> > @michellema1208 donation history page shouldn't be affected by this PR at all - that's an indexer-populated page.
> 
> @vacekj cool, thank you! Does that mean that donations made within this PR would show up on the Donation History page? Or is additional Indexer work needed in order to support that? +@boudra

yes they should show up, I think what @vacekj meant to say was that the history page was not modified in this PR therefore it should be working as normal

2024-02-29 21:50 UTC, vacekj commented
exactly @michellema1208, the donation history page is not modified in this PR, so any bugs there warrant a new ticket.

2024-03-01 09:28 UTC, gravityblast approved these changes

2024-03-01 11:35 UTC, boudra approved these changes

2024-03-01 11:35 UTC, merged