Feedback fixes for 2962
gitcoinco/grants-stack pull request #3029
Opened 2024-02-23 13:46 UTC by codenamejason

## Description

Address feedback on merged PR

## Checklist

This PR:

- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-02-24 05:59 UTC, thelostone-mc commented on packages/builder/src/actions/rounds.ts
> +      programName: v2Round.roundMetadata.name,
Ah okie this is cleaner !
@0xKurt I think the reason why we had this confusion was we used a random metadata in our script which didn't have name in the round metadata (which caused the breakage)

2024-02-24 05:59 UTC, thelostone-mc approved these changes

2024-02-27 09:43 UTC, thelostone-mc commented on packages/builder/src/actions/projects.ts
> -      });
^ If we do this, we might have to figure out how to get the round program name for applications

2024-02-27 11:59 UTC, thelostone-mc commented on packages/builder/src/actions/rounds.ts
> +      programName: v2Round.roundMetadata.name,
```suggestion
      programName: v2Round.project?.name,
```

2024-02-27 13:41 UTC, thelostone-mc commented on packages/builder/src/actions/projects.ts
> -      });
Okie this can be removed. Makes sense. Doesn't seem to be used anywhere

2024-02-27 13:45 UTC, thelostone-mc commented on packages/builder/src/components/rounds/ViewApplication.tsx
> +  const roundInReview = props.roundApplicationStatus === "PENDING";
Why did we change this ?

2024-02-27 14:05 UTC, boudra requested changes
just the V2RoundWithProject name, everything looks great

2024-02-27 14:05 UTC, boudra commented on packages/data-layer/src/data.types.ts
> +export type V2RoundWithProjects = V2RoundWithRoles & {
```suggestion
export type V2RoundWithProject = V2RoundWithRoles & {
```

2024-02-27 14:05 UTC, boudra commented on packages/builder/src/actions/rounds.ts
> -    const programName = isV1
nice one

2024-02-27 14:51 UTC, boudra approved these changes

2024-02-27 16:12 UTC, merged