manager: Create programs for allo v1 and v2
gitcoinco/grants-stack pull request #3030
Opened 2024-02-23 14:02 UTC by boudra

Fixes: #2976 
## Description

ended up mostly deleting code 🙌 

- add createProgram allo method
- implement create program for v1 (program factory) v2 (create profile)
- add `type: program` to the metadata so we can distinguish projects from programs
- Remove create program context in favour of simple hook
- remove context unit test in favour of create program page integration test

# How to test

Loom: https://www.loom.com/share/2ea73c01bb09415a97f6e22a083b822b

Note: Profiles created in Builder will not show up in manager anymore.

1. Create a program in Allo V2, it should show up, try with multiple operators
2. Repeat for Allo V1

## Checklist

This PR:

- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't disable eslint rules.
- [x] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [x] Doesn't contain commented out code.
- [x] If adding/updating a feature, it adds/updates its test script on Notion.

2024-02-23 18:56 UTC, michellema1208 requested changes
@boudra I'm able to create programs on v1 and v2, but for v2, it seems like it's only displaying the third program I created (left) and the first program I created (right): 

<img width="1435" alt="Screen Shot 2024-02-23 at 1 51 17 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/f6e06cbf-c8eb-46d0-ad9a-b611afd61c57">

There should be 3 programs total - see Etherscan: https://sepolia.etherscan.io/address/0x37e5e6eb36467f98392ebbb35f110fbb8238e6d3. Nothing changes when I refresh the page. 

I also added you as a round operator to all 3 rounds if you want to investigate! 

-------
This only happened once, but the first time I created a program, I wasn't able to open the v2 program - but then I couldn't reproduce this after creating a second program. Not sure if this is an anomaly, or if it only happens the first time you create a program. 

<img width="1437" alt="Screen Shot 2024-02-23 at 1 44 12 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/e25537c8-2ead-49d6-b348-6075b1623d71">

2024-02-23 19:34 UTC, boudra commented
@michellema1208 those issues are indexer related I created two issues to investigate further.

The reason the first program didn't load when you clicked it is because of an intermittent error from cloudfront: https://github.com/gitcoinco/grants-stack-indexer/issues/463

the reason your second program wasn't picked up is a tricky one, I am still investigating it, I suspect it's an intermittent Sepolia RPC issue on the indexer side. I just tried making 3 programs and they were all created for me https://github.com/gitcoinco/grants-stack-indexer/issues/462

I would suggest merging this PR as there's nothing we can do to fix those issues in Grants stack

2024-02-26 04:59 UTC, thelostone-mc approved these changes

2024-02-26 13:51 UTC, melissa-neira approved these changes
lgtm!

2024-02-26 18:19 UTC, michellema1208 approved these changes

2024-02-26 18:22 UTC, merged