Apply to Direct Round
gitcoinco/grants-stack pull request #3034
Opened 2024-02-23 20:20 UTC by codenamejason

Fixes: #2943 

## Description

## Checklist

This PR:

- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-02-26 22:51 UTC, vacekj approved these changes

2024-02-27 13:51 UTC, thelostone-mc approved these changes

2024-02-27 16:04 UTC, michellema1208 requested changes
@codenamejason / @0xKurt / @thelostone-mc - when I load Builder, it looks like all projects on Allo v2 are not loading, which blocks me from being able to test apply to a round. This is because it creates an infinite loop - if I create a new project, it still doesn't show up, and the application asks me to create a project again. 

Link: https://builder-staging-git-2943-apply-to-direct-round-grants-stack.vercel.app/#/projects 

<img width="1440" alt="Screen Shot 2024-02-27 at 10 57 37 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/1944664b-10b6-4670-99d2-af222aa09b6d">

I trust that this was tested before being moved to QA, but gentle reminder to test the core flow and ensure it's working before moving to QA. 

Additionally, can you add the following details to the testing guidelines? 
1. Should we be testing only projects on the same chain? Or is testing applying with projects on different chains in scope for this PR? 
2. After I apply to a round, is viewing the application (i.e. clicking into the application and seeing project details and application questions) in scope for this PR? 
3. For the round that is included in the testing guidelines (https://builder-staging-git-2943-apply-to-direct-round-grants-stack.vercel.app/#/chains/80001/rounds/17), can you please share the Manager link for this round? That way, those testing can verify if the application came through on debug mode.

2024-02-27 18:24 UTC, michellema1208 commented
@codenamejason / @0xKurt / @thelostone-mc - I applied to a round, but the application is not appearing in the "My Applications" section, which is in the core flow and outlined in the testing guidelines above. Want to stress that it would be really helpful to test the core flow and ensure it's working before moving to QA! This creates some repetitive work on my part, as I will need to retest applications E2E again. Thank you in advance + I appreciate you all! 

Successful tx: 0x74e4052a02d48233ab4ed47dc815c3a8c344252f529f1f0b2149f645e2032630

Builder link: https://builder-staging-git-2943-apply-to-direct-round-grants-stack.vercel.app/#/chains/80001/registry/0x/projects/0xefeeb09068a75fdd337ad4e4d86d64705370ec89130b5b2be04307551e349c2e

<img width="1432" alt="Screen Shot 2024-02-27 at 1 16 15 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/e7a32427-c315-4ca9-a9f4-a7f663306d39">

2024-02-27 20:44 UTC, michellema1208 approved these changes
@codenamejason @0xKurt @thelostone-mc - confirming this is now working according to testing guidelines! 

One question: since this PR just said to test on Mumbai, I did not test the use case of applying with a project on a different chain (i.e. Sepolia project -> Polygon Mumbai round). If that's needed in order to merge the PR, please indicate so and I can test that use case as well. 

Other than that, great work!!

2024-02-27 21:14 UTC, merged