chore: add usd glo
gitcoinco/grants-stack pull request #3075
Opened 2024-03-04 04:42 UTC by thelostone-mc

## Description

fixes https://github.com/gitcoinco/grants-stack/issues/3074

2024-03-04 14:17 UTC, melissa-neira approved these changes

2024-03-04 15:00 UTC, codenamejason approved these changes

2024-03-04 15:03 UTC, michellema1208 requested changes
@thelostone-mc - I tried creating two rounds with USDGLO token as the payout token, but the rounds aren't showing up in my Program for me for some reason. 

GS Program on Polygon: https://manager-git-usd-glow-grants-stack.vercel.app/#/program/0x1caaef21f34d5158d2e13d40327952649acd9338?debug=true

Successful tx for first round: https://polygonscan.com/tx/0x05d1ff3e01d6de2016d5cb8508757cb1de8b298794842689e16b2b9555064b43 

Successful tx for second round: https://polygonscan.com/tx/0x35fbaf535f2d60f5e29c00ffe092cb7db87dd088ccdbe45b6f8f67eaf1e1c82b 

I also created a Polygon round on prod (using MATIC as payout token since USDGLO isn't available yet), and the round was created successfully and did show up in the UI, so I believe the issue is specific to this PR: https://polygonscan.com/tx/0x1dfc3234f5353a85c961020236f742802bb0e642778df084661e76edf4b236f5

2024-03-06 11:30 UTC, gravityblast approved these changes

2024-03-11 14:40 UTC, michellema1208 approved these changes

2024-03-11 18:49 UTC, merged