wip
gitcoinco/grants-stack pull request #3090
Opened 2024-03-05 17:31 UTC by thelostone-mc

Fixes: #issue

## Description

## Checklist

This PR:

- [ ] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-03-05 20:32 UTC, codenamejason commented on packages/common/src/allo/backends/allo-v1.ts
> +      }
@bhargavaparoksham you hit the nail on the head

2024-03-11 09:52 UTC, 0xKurt approved these changes

2024-03-11 16:45 UTC, codenamejason approved these changes

2024-03-12 10:18 UTC, gravityblast commented
I think we need to rebase otherwise I see an error in the console: `Cannot query field "isReadyForPayout" on type "Round"`

2024-03-12 13:05 UTC, thelostone-mc commented on packages/common/src/allo/backends/allo-v1.ts
> +        return error(new AlloError("roundId must be Hex"));
round Id would be Hex for v1 right ? for v2, it's a number

2024-03-13 06:56 UTC, boudra approved these changes

2024-03-13 13:09 UTC, michellema1208 requested changes
@thelostone-mc @0xKurt @codenamejason sharing testing results so far 

### Edit a DG round created on allo-v1
No issues, good work! 

### Edit a QF round created on allo-v1
- [ ] Not able to edit round start date to be before an application end date (i.e. overlapping application and round dates), even if the current round start date has not passed 

### Edit a DG round created on allo-v2
- [ ] Not able to update round start date when the start date has passed

### Edit a QF round created on allo-v2
- [ ] Not able to edit application or round dates, even if dates have not passed

2024-03-13 13:34 UTC, thelostone-mc commented
>  Not able to edit round start date to be before an application end date (i.e. overlapping application and round dates), even if the current round start date has not passed

Just tested this out and it worked on staging
<img width="794" alt="image" src="https://github.com/gitcoinco/grants-stack/assets/5358146/3269de70-15a6-41f3-b862-82f920f52f3a">

> Not able to edit application or round dates, even if dates have not passed

This works as well

2024-03-13 16:12 UTC, michellema1208 approved these changes

2024-03-13 16:14 UTC, merged