V2 Donations
gitcoinco/grants-stack pull request #3116
Opened 2024-03-11 22:33 UTC by 0xKurt

Fixes: #issue

## Description

## Checklist

This PR:

- [ ] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-03-15 07:43 UTC, thelostone-mc approved these changes

2024-03-15 08:15 UTC, boudra commented on packages/common/src/allo/backends/allo-v2.ts
> +  async donate(
🙏

2024-03-15 08:24 UTC, boudra commented on packages/common/src/allo/backends/allo-v2.ts
> +      throw new Error(
```suggestion
      throw new AlloError(
```

2024-03-18 13:07 UTC, boudra approved these changes

2024-03-18 14:58 UTC, michellema1208 requested changes
@0xKurt / @thelostone-mc / @codenamejason - I'm having trouble adding different projects across different rounds to the same cart -- it seems like adding a project in one round to a cart triggers adding a different project in a different round to cart as well, and also the projects don't appear in the same cart. Same things happens when I try to add the same project across different rounds to the same cart. 

Expected behavior: I am able to add different projects from different rounds to the same cart on v2. If I add the same project from two different rounds to the same cart, I see the same project in my cart twice, once in each round. 

Loom: https://www.loom.com/share/4891940b8095410a83295a7b9c767c68?focus_title=1&muted=1&from_recorder=1

2024-03-19 15:27 UTC, michellema1208 approved these changes
LGTM - great work Kurt and team!

2024-03-19 15:36 UTC, merged