Finalize Round V1 / V2
gitcoinco/grants-stack pull request #3119
Opened 2024-03-12 08:04 UTC by boudra

fixes https://github.com/gitcoinco/grants-stack/issues/2981
fixes https://github.com/gitcoinco/grants-stack/issues/2978
fixes https://github.com/gitcoinco/grants-stack/issues/2979

## Description

This one is a bit difficult to QA because of the many steps involved in creating a finalizable round. I have done those steps and recorded a Loom finalizing a round: https://www.loom.com/share/6aaadd27f07846c8bbf1c2e12b6c3592

I tested in local because I had to hack a few things to get some proper matching results with the amount of votes I had.

At the end of the video I noticed that the Fund Grantees page was not working, I found the issue and fixed it:
<img width="1182" alt="Screenshot 2024-03-13 at 13 28 46" src="https://github.com/gitcoinco/grants-stack/assets/711886/c7d45e9f-9410-4cda-83b6-4efd9d20fb9f">

I also paid out a grantee to make sure the uploaded Merkle root is valid:

<img width="1206" alt="Screenshot 2024-03-13 at 13 46 30" src="https://github.com/gitcoinco/grants-stack/assets/711886/c97072e8-01f4-4879-9c07-93b0675ae831">

I suggest that we leave the QA for Allo v2 when we do the internal E2E round next week, just because the donation flow for Allo v2 is not done yet.

## How to test

- Create a finalizable round (create round, apply, approve, vote, fund, wait for round end)
- Click on Finalize matches
- Verify that payout screen is available
- Verify that finalized matches show

## Checklist

This PR:

- [x] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [x] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [x] Doesn't disable eslint rules.
- [x] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [x] Doesn't contain commented out code.
- [x] If adding/updating a feature, it adds/updates its test script on Notion.

2024-03-13 07:50 UTC, bhargavaparoksham approved these changes
Other than the leftover console log, lgtm!

2024-03-13 07:50 UTC, bhargavaparoksham commented on packages/common/src/index.ts
> +  console.log(roundId, chainId);
leftover console log?

2024-03-13 08:02 UTC, boudra commented on packages/common/src/index.ts
> +  console.log(roundId, chainId);
whoops

2024-03-13 13:44 UTC, thelostone-mc approved these changes

2024-03-13 15:30 UTC, michellema1208 requested changes
@boudra I'm seeing the "estimated matching %" on the Round Stats page is coming up as 0%, even though all projects in my round have received donations from 2 or more unique donors. I remember in the past, usually I would see a nonzero estimate % here - is that right? 

Link: https://manager-staging-git-finalize-round-grants-stack.vercel.app/#/round/0x8a44288efdc9fe593f633fb447fcfb85770c0d57 

<img width="1422" alt="Screen Shot 2024-03-13 at 11 28 33 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/84e982dc-37b1-48bf-bac5-73c60dfee886">

2024-03-14 03:57 UTC, boudra commented
> @boudra I'm seeing the "estimated matching %" on the Round Stats page is coming up as 0%, even though all projects in my round have received donations from 2 or more unique donors. I remember in the past, usually I would see a nonzero estimate % here - is that right? I noticed that your round also had a 0% matching distribution on the Round Stats page ... so maybe this is expected?
> 
> Link: https://manager-staging-git-finalize-round-grants-stack.vercel.app/#/round/0x8a44288efdc9fe593f633fb447fcfb85770c0d57
> <img alt="Screen Shot 2024-03-13 at 11 28 33 AM" width="1422" src="https://private-user-images.githubusercontent.com/26017180/312521484-84e982dc-37b1-48bf-bac5-73c60dfee886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODY3MTIsIm5iZiI6MTcxMDM4NjQxMiwicGF0aCI6Ii8yNjAxNzE4MC8zMTI1MjE0ODQtODRlOTgyZGMtMzdiMS00OGJmLWJhYzUtNzNjNjBkZmVlODg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAzMjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNTAyN2UwYmNmODZmMDExYzE3ZDdlYWZlYzZjNmRhYmUzZjBlZGE2NWYxNTQzOGVkYjMxZjQ0NmU5NTRjOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cv99qRFl_1ECQFfPSqk1iPlwTBQCT8QC0Mri5wgUDx0">

The address `0x1fd06f088c720ba3b7a3634a8f021fdd485dca42` has a passport score of 0 and the round has passport enabled, those votes are not counted unfortunately. You should be able to fix it by increasing the score to 15.

2024-03-14 13:07 UTC, michellema1208 commented
@boudra ohh gotcha - that's my bad! Let me go ahead and continue testing then

2024-03-14 18:25 UTC, michellema1208 approved these changes

2024-03-14 18:48 UTC, michellema1208 commented
@boudra I approved the PR for now - shared some more context in Discord DMs! We'll definitely make sure to test this flow in our internal testing week next week. 

One question: am I supposed to be able to revise results before the contract has been funded or the round has ended? I uploaded a revised CSV where I gave all of my donations matching, but still seeing 0% matching distribution.

2024-03-15 05:09 UTC, merged