Release Allo V2 🚀
gitcoinco/grants-stack pull request #3137
Opened 2024-03-14 08:36 UTC by boudra

fixes https://github.com/gitcoinco/grants-stack/issues/3126
fixes https://github.com/gitcoinco/grants-stack/issues/3125
fixes https://github.com/gitcoinco/grants-stack/issues/3124
fixes https://github.com/gitcoinco/grants-stack/issues/3123
fixes https://github.com/gitcoinco/grants-stack/issues/3127

before merging:
- [ ] change default ALLO_VERSION env var to v2 in Vercel
- [x] set up explorer-v1.gitcoin.co

2024-03-15 06:40 UTC, thelostone-mc approved these changes

2024-03-15 13:12 UTC, bhargavaparoksham reviewed
codewise looks good. 

@boudra fyi In the UI i'm able to toggle between v1 & v2 in staging but i'm not able to toggle in prod.

2024-03-18 13:22 UTC, melissa-neira approved these changes
looks good to me!

2024-03-20 18:04 UTC, michellema1208 requested changes
hey @boudra - sharing some quick feedback testing the switch between v1/v2: 

**Functionality**
- [ ] On both Builder and Manager, it seems like the switch to v1 is not working -- when I select v1, the page reloads but then I'm still connected to v2. Similarly if I'm on Manager on v2 > click on v1 round --> I'm stuck in an infinite loop of switching to v1. 

**UI** + @melissa-neira for feedback as well 

- [ ] I'm noticing that the white dropdown blends in with the Builder background given Builder is default white background. Should we add an outline or the grey shading that we have for the switch dropdown on Manager?

<img width="947" alt="Screen Shot 2024-03-20 at 1 13 45 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/23ce9cf7-0569-4494-8e81-720d23d4891c">

- [ ] Speaking of Manager, it seems like the dropdown UI across Builder and Manager is inconsistent - which fonts/patterns should we stick too? 

Builder: 
<img width="947" alt="Screen Shot 2024-03-20 at 1 13 45 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/23ce9cf7-0569-4494-8e81-720d23d4891c">

Manager: 
<img width="1418" alt="Screen Shot 2024-03-20 at 1 20 22 PM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/37bd3a39-215d-46fc-bee5-ff1f39355226">

- [ ] Explorer Donation History page is showing different stats on v2 versus v1 -- my understanding is that on both sites you should see all of your donations across v1 and v2?

I'm seeing different stats when I load the same contributor profile on: 

- https://explorer-git-allo-migration-grants-stack.vercel.app/#/contributors/0x37e5e6eb36467F98392ebBb35F110FbB8238e6D3
- https://explorer-v1.gitcoin.co/#/contributors/0x37e5e6eb36467F98392ebBb35F110FbB8238e6D3

2024-03-21 01:30 UTC, thelostone-mc commented on packages/grant-explorer/src/features/api/AlloWrapper.tsx
> -          allo: zeroAddress,
^ this seem to be breaking builder

2024-03-21 07:57 UTC, boudra commented
@michellema1208 

- the switcher is now fixed
- i made the dropdown slightly grey-ish on builder (@melissa-neira please let me know if that's fine or you want to do something else!)
- fonts should now be consistent across app to use DM Mono
- stats should now be the same, the difference was just because v1 was also loading testnets, but they are both showing v1 and v2

2024-03-21 13:38 UTC, michellema1208 approved these changes

2024-03-25 08:50 UTC, merged