Feat/report card share and edit
gitcoinco/grants-stack pull request #3199
Opened 2024-03-24 10:04 UTC by cristinalare

Fixes: https://github.com/gitcoinco/grants-stack/issues/2909

## Description

This PR includes:

Branding updates for round & application pages

Report card integration in the round page:

- Added new /round/:chainId/:roundId/stats page which includes: page description, round stats, projects plot, tweets section and leaderboard. 

- Round operators can edit the page description & the tweets.

- Share page on warpcast & twitter. In order to have a dynamic twitter card / OG image, we'll be using reportcards.gitcoin.co project:

 - after merging this PR or this one https://github.com/gitcoinco/grants-stack/pull/3147, we'll have to change reportcards.gitcoin.co domain to share.gitcoin.co, update that project to have the OG image matching the explorer designs (already done, i just need to merge the update when this branch is merged)
 -  the intent will include a link 

Todo after this PR will be merged:
a. Add "What people are tweeting" section and allow round operator to update stats page description/preamble & tweets/farcaster list
b. Add share button & support for dynamic twitter card for the stats page - share to twitter be a link to previous report cards (which have dynamic twitter card) and the previous report cards pages will redirect to explorer
Designs: [Figma](https://www.figma.com/file/5m4EgbkSCMVgc2eSAa18rB/Report-Cards?type=design&node-id=81-3287&mode=design)

## Checklist

This PR:

- [ ] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-03-25 06:00 UTC, thelostone-mc approved these changes

2024-03-26 11:09 UTC, melissa-neira requested changes
hey @cristinalare, I'm noticing some odd things both on the explorer homepage and on the round page. 

first on the explorer homepage: (I'm not sure if this is related to this PR or not, but wanted to call it out just in case)
- there are no QF rounds at all showing
- there's something weird going on with the QF labels. see here:
<img width="1404" alt="Screenshot 2024-03-25 at 12 41 19" src="https://github.com/gitcoinco/grants-stack/assets/87520659/e07305c6-4ea4-47ac-a095-399812e5878f">

round page:
- project cards are really wide. project cards should look like [this](https://www.figma.com/file/c4UCPzbLnK3kz67M6R9VGN/Explorer-S20?type=design&node-id=103-7994&mode=design&t=rZTSaCcwRdlFV4Hl-4) when in a normal browser width.
this is how they currently look:
<img width="1430" alt="Screenshot 2024-03-25 at 12 42 30" src="https://github.com/gitcoinco/grants-stack/assets/87520659/a5562d92-bd4b-4afd-b5e1-b8b9df1a5b52">

2024-04-08 13:38 UTC, melissa-neira requested changes
looks good to me, just one change :) - the tabs don't have enough space between them. there should be 32px of space. see [here](https://www.figma.com/file/5m4EgbkSCMVgc2eSAa18rB/Report-Cards?type=design&node-id=287-2476&mode=design&t=NdYDULKEfDLQ6Nge-4)

2024-04-09 22:02 UTC, cristinalare commented
> looks good to me, just one change :) - the tabs don't have enough space between them. there should be 32px of space. see [here](https://www.figma.com/file/5m4EgbkSCMVgc2eSAa18rB/Report-Cards?type=design&node-id=287-2476&mode=design&t=NdYDULKEfDLQ6Nge-4)

this is done, thanks Melissa!

2024-04-18 15:09 UTC, closed without merging