2919/disable matching stats for avax
gitcoinco/grants-stack pull request #3239
Opened 2024-03-26 23:02 UTC by codenamejason

Fixes: #2919 

## Description

## Checklist

This PR:

- [ ] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-03-27 06:52 UTC, thelostone-mc approved these changes

2024-03-27 22:05 UTC, michellema1208 commented
@codenamejason do you have a live Avalanche round with Passport turned on that I could use to test? If not, would you be able to send in some applications to this round: https://manager.gitcoin.co/#/round/7 so we can test? I'm low on AVAX and can't apply rn. If you don't have AVAX handy, I'll look into bridging some funds tomorrow

2024-03-28 16:03 UTC, michellema1208 requested changes
hey @codenamejason - thank you for getting started on this! 

Running into two issues: 
1. I'm still seeing matching estimates on Avalanche on the cart page - I shouldn't see any matching, not even $0.00 on the cart page for rounds on Avalanche 

<img width="1438" alt="Screen Shot 2024-03-28 at 11 58 21 AM" src="https://github.com/gitcoinco/grants-stack/assets/26017180/218b296b-9196-4ff5-b9aa-1bce286b2873">

2. When I try donating to an Arbitrum round alongside the Avalanche round, I'm not able to enter the donation amount for the project in the Arbitrum round. This is only happening in this PR - not happening on prod. 

To reproduce: 
1. Add projects from this Avax round to cart: https://explorer-git-2929-disable-avax-match-stats-grants-stack.vercel.app/#/round/43114/7 
2. Add projects from this Arbitrum round to cart: https://explorer-git-2929-disable-avax-match-stats-grants-stack.vercel.app/#/round/42161/11
3. Try entering in donation amount on the specific project (not via Apply all) 
4. Notice you can't remove the 0 default donation amount, you can only change donation amount via Apply to all

2024-03-28 17:21 UTC, michellema1208 commented
@codenamejason I'm actually not sure that we need to make changes on Manager side -- would be good to have @gravityblast weigh in as Tech Lead here! I just checked the view on prod for the test Avax round (https://manager.gitcoin.co/#/round/7) and it just displays 0% matching, which makes sense to me. The Avax team knows that results will be calculated off-platform with Umar, and will be uploaded separately. wdyt @gravityblast ?

2024-04-10 13:15 UTC, thelostone-mc approved these changes

2024-04-11 02:32 UTC, merged