match style for Passport widget to new designs
gitcoinco/grants-stack pull request #3305
Opened 2024-04-16 14:09 UTC by bhargavaparoksham

Fixes: #3238 

## Description

Explorer: match style for Passport widget to new designs

## Checklist

This PR:

- [ ] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-04-17 17:36 UTC, melissa-neira commented
@bhargavaparoksham I'm having a hard time testing this because none of the rounds that are active right now have passport activated. unless that's a bug?

2024-04-18 09:32 UTC, melissa-neira requested changes
lgtm except for one small thing: the font for the scores in the widget should be modern era/regular/20px

in staging:
<img width="357" alt="Screenshot 2024-04-18 at 11 24 40" src="https://github.com/gitcoinco/grants-stack/assets/87520659/04ddcd82-84b6-49ee-bbbb-ec5758d62a31">

in figma:
<img width="387" alt="Screenshot 2024-04-18 at 11 26 27" src="https://github.com/gitcoinco/grants-stack/assets/87520659/b0ed5216-c9f2-43f4-bec0-55c024aa7c4e">

2024-04-18 10:26 UTC, melissa-neira approved these changes
lgtm!

2024-04-18 10:29 UTC, thelostone-mc approved these changes

2024-04-18 10:29 UTC, merged