Manager changes for Passport Lite x Cluster Match MVP
gitcoinco/grants-stack pull request #3336
Opened 2024-04-19 07:33 UTC by bhargavaparoksham

Fixes: #3131 

## Description

Manager: frontend changes for Passport Lite x Cluster Match MVP

## Checklist

This PR:

- [ ] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-04-29 14:34 UTC, boudra commented on packages/round-manager/src/features/api/types.ts
> +      sybilDefense?: SybilDefence;
one is spelled defence the other defense

2024-05-03 15:36 UTC, melissa-neira requested changes
some quick call outs:

<img width="990" alt="Screenshot 2024-05-03 at 17 28 53" src="https://github.com/gitcoinco/grants-stack/assets/87520659/a4439b8f-9242-4d57-b51c-983ebaa505a8">
- put a space after the link
<br>
- when you hover over "recommended" there's an underline interaction that makes it look like it could be a link. remove hover interaction.
<br>
- the link to the cluster match docs should open in a new tab, otherwise it might cause user confusion
<br><br>
- it's not very clear to me how to get the round address and round ID from the links you provided in order to input that into the notebook. can you please provide a clearer way to test this?

2024-05-06 13:05 UTC, melissa-neira approved these changes
lgtm!

2024-05-07 13:55 UTC, boudra approved these changes

2024-05-08 02:17 UTC, merged