Feat: round & application page design updates
gitcoinco/grants-stack pull request #3337
Opened 2024-04-19 10:20 UTC by cristinalare

Fixes: https://github.com/gitcoinco/grants-stack/issues/2909

## Description

Branding updates for round & application pages - Designs: [Figma](https://www.figma.com/file/5m4EgbkSCMVgc2eSAa18rB/Report-Cards?type=design&node-id=81-3287&mode=design)

## Checklist

This PR:

- [ ] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-04-19 21:09 UTC, thelostone-mc approved these changes

2024-04-22 00:32 UTC, meglister requested changes
Styling changes look great!

However -- the links to report cards are not working. I think they are using the profile ID to generate the URL and the report card app requires the contract ID.

To repro:
- Go to earthist round here: https://explorer-staging-git-fork-cristinalare-feat-37883c-grants-stack.vercel.app/#/round/42161/35
- Observe this link loads https://reportcards.gitcoin.co/42161/35
- Report card is actually located at https://reportcards.gitcoin.co/42161/0x6a4122E7acCBE88e0792c73Fb32133fCA584ebB7

2024-04-22 07:59 UTC, cristinalare commented
> Styling changes look great!
> 
> However -- the links to report cards are not working. I think they are using the profile ID to generate the URL and the report card app requires the contract ID.
> 
> To repro:
> 
> * Go to earthist round here: https://explorer-staging-git-fork-cristinalare-feat-37883c-grants-stack.vercel.app/#/round/42161/35
> * Observe this link loads https://reportcards.gitcoin.co/42161/35
> * Report card is actually located at https://reportcards.gitcoin.co/42161/0x6a4122E7acCBE88e0792c73Fb32133fCA584ebB7

@meglister the issue is that report cards aren't handling allo v2 rounds because it wasnt maintained since allo v2 release, so this will have to be fixed from the report cards project while keeping the same URL structure (reportcards.gitcoin.co/chainId/roundId) in the explorer - im currently working on getting the new version live asap

2024-04-23 13:21 UTC, meglister approved these changes

2024-04-24 04:03 UTC, merged