add GTC to voting tokens
gitcoinco/grants-stack pull request #3425
Opened 2024-05-09 07:00 UTC by cristinalare

Fixes: #issue

## Description

## Checklist

This PR:

- [ ] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-05-09 07:07 UTC, thelostone-mc requested changes
Could you point out which issue or conversation this discussion happened?

2024-05-09 07:24 UTC, cristinalare commented
> Could you point out which issue or conversation this discussion happened?

i updated the description!

2024-05-09 12:12 UTC, codenamejason approved these changes

2024-06-05 15:18 UTC, 0xKurt commented
closed in behalf of
https://github.com/gitcoinco/gitcoin-chain-data/blob/de488758667aa01809ef1be84cf4a6089f29f96d/src/data/chains/42161/chain.ts#L86
and 
https://github.com/gitcoinco/grants-stack/pull/3474

2024-06-05 15:18 UTC, closed without merging