View team members as an Admin in Manager
gitcoinco/grants-stack pull request #3446
Opened 2024-05-16 13:36 UTC by bhargavaparoksham

Fixes: #2732 
Fixes: #2735 

View team members as an Admin in Manager

## Checklist

This PR:

- [ ] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-05-22 15:44 UTC, thelostone-mc approved these changes

2024-05-22 15:45 UTC, thelostone-mc reviewed
meh

2024-05-22 15:45 UTC, thelostone-mc commented on packages/round-manager/src/features/round/ViewManageTeam.tsx
> +  console.log("INDE", indexingStatus)
```suggestion
```

2024-05-22 15:45 UTC, thelostone-mc commented on packages/round-manager/src/features/round/ViewManageTeam.tsx
> +  console.log("CON", contractUpdatingStatus)
```suggestion
```

2024-05-22 15:45 UTC, thelostone-mc commented on packages/round-manager/src/features/round/ViewManageTeam.tsx
> +  console.log("TEAM", isTeamMembersLoading)
```suggestion
```

2024-05-23 15:22 UTC, melissa-neira approved these changes
everything looks and works great! my one call out is that it is annoying that after you add a member, the page refreshes and you are taken to the grant applications tab. is there any way for the page to refresh to the same tab (manage team)?

2024-05-23 15:23 UTC, melissa-neira requested changes
oops, meant to request changes!

everything looks and works great! my one call out is that it is annoying that after you add a member, the page refreshes and you are taken to the grant applications tab. is there any way for the page to refresh to the same tab (manage team)?

2024-05-27 07:14 UTC, merged