Single .env file
gitcoinco/grants-stack pull request #3467
Opened 2024-05-27 10:14 UTC by gravityblast

Fixes: #issue

## Description

## Checklist

This PR:

- [ ] Does it add new payout or donation token? In this case, have they been added to the indexer to avoid it to crash?
- [ ] Includes only changes relevant to the original ticket. Significant refactoring needs to be separated.
- [ ] Doesn't disable eslint rules.
- [ ] Doesn't work around the type checker (including but not limited to: type casts, non-null assertions, `@ts-ignore`, unjustified optional values).
- [ ] Doesn't contain commented out code.
- [ ] If adding/updating a feature, it adds/updates its test script on Notion.

2024-05-27 19:32 UTC, MasterHW commented on .env.example
would like to see this merged with https://github.com/gitcoinco/grants-stack/blob/streamline-env/.env.example

2024-05-27 19:36 UTC, MasterHW requested changes
i like the new IPFS/Pinata distinction. approved w/ one request

2024-05-28 16:29 UTC, MasterHW approved these changes
all good!

2024-05-29 05:20 UTC, thelostone-mc approved these changes
Do we need to make changes on env in production ?

2024-05-29 07:56 UTC, merged