feat(graph): create a local hardhat + graph-node docker compose
gitcoinco/grants-stack pull request #574
Opened 2022-10-27 16:14 UTC by vacekj

@thelostone-mc @nfrgosselin I need some additional clarification on #234. What I added in this PR is a docker compose, than when run, will spin up a local hardhat node, which you can deploy contracts against, then spin up a graph-node against anvil. Then you should be able to deploy contracts as usual, interact with them and the subgraph should pick everything up. I haven't yet set-up the Anvil node as a hardhat network, since I first want to get confirmation that this is the right way to go about this.

EDIT: replace anvil node with hardhat node

##### Refers/Fixes

fixes #234

2022-10-28 06:16 UTC, thelostone-mc commented
Questions: 

- can we not use the hardhat node as opposed to relying on anvil ?
- additionally to deploy the contracts on local chain -> I'm assuming we'd need to write up a script for that as well right ?

2022-11-01 14:07 UTC, melissa-neira commented
Defer to engineering 🕺

2022-11-01 14:23 UTC, thelostone-mc commented
Could we add in documentation on the graph/README on how to run this ?

2022-11-01 16:10 UTC, nfrgosselin reviewed
Defer to engineering review

2022-11-02 16:07 UTC, hmrtn commented
Docker compose looks good and runs just fine with frequent block updates. 

It appears to be using hardhat rather than anvil - is this correct?

2022-11-02 16:07 UTC, hmrtn approved these changes

2022-11-02 17:28 UTC, nfrgosselin approved these changes
defer to engineering approval

2022-11-02 18:31 UTC, thelostone-mc commented on packages/graph/docker-compose.yml
> +      # workaround for https://github.com/docker/for-mac/issues/6270?
^ Is this needed ?

2022-11-02 18:32 UTC, thelostone-mc requested changes
could we update the documentation to state how to run this  + update the PR message to state we are using hardhat node and not anvil

2022-11-03 10:46 UTC, vacekj commented on packages/graph/docker-compose.yml
> +      # workaround for https://github.com/docker/for-mac/issues/6270?
Removed

2022-11-03 10:46 UTC, vacekj commented
> Docker compose looks good and runs just fine with frequent block updates.
> 
> It appears to be using hardhat rather than anvil - is this correct?

That is correct, updated PR text to reflect this change.

2022-11-07 08:56 UTC, thelostone-mc approved these changes

2022-11-07 09:05 UTC, merged